import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>İlkem Dijital - Ana Sayfa</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link crossOrigin rel="preconnect" href="https://fonts.googleapis.com"></link>
        <link crossOrigin rel="preconnect" href="https://fonts.gstatic.com"></link>
        <link crossOrigin href="https://fonts.googleapis.com/css2?family=Montserrat:wght@700&display=swap" rel="stylesheet"></link>
      </Head>

      <div className={styles.main}></div> 
    </div>
  )
}
